# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2025 Carles Fernandez-Prades <carles.fernandez@cttc.es>

# Keep GitHub Actions up to date with GitHub's Dependabot

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: next
    groups:
      github-actions:
        patterns:
          - "*"  # Group all Actions updates into a single larger pull request
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"